name: Docker CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile'
      - 'app.js'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - run: docker build -t dockerized_app:test .

      - run: |
          docker run -d -p 3000:3000 --name test-app dockerized_app:test
          sleep 5
          curl -f http://localhost:3000
          docker logs test-app
          docker stop test-app

      - run: |
          docker tag dockerized_app:test ${{ secrets.DOCKERHUB_USERNAME }}/dockerized_app:latest
          docker tag dockerized_app:test ${{ secrets.DOCKERHUB_USERNAME }}/dockerized_app:${{ github.sha }}

      - run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockerized_app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockerized_app:${{ github.sha }}
